-- phpMyAdmin SQL Dump
-- version 5.3.0-dev+20220609.11e34a6fec
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 19, 2022 at 06:09 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project_film`
--

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `release_date` date NOT NULL,
  `vote_count` int(11) NOT NULL,
  `vote_average` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`id`, `title`, `genre`, `image`, `description`, `release_date`, `vote_count`, `vote_average`) VALUES
(121, 'Fantastic Beasts: The Secrets of Dumbledore', '6', 'https://image.tmdb.org/t/p/w200/kzz0tk84vio6il1s0mOdJOwVPQV.jpg', 'Film yang juga dikenal dengan Fantastic Beast 3 ini akan mengawali kisahnya dari Newt Scamander yang menolong qilin. Ini adalah hewan ajaib yang bisa mengetahui ketulusan hati seseorang.\r Namun dalam proses penyelamatannya, ia dihadang anak buah Grindelwald. Mereka berhasil menghabisi induk qilin dan satu anaknya, sementara kembaran si anak qilin berhasil dibawa Scamander.\r Inilah yang nantinya akan menjadi misi penyelamatan dunia yang unik dari kejahatan Grindelwald.\r Albus Dumbledore tak tinggal diam. Ia membentuk pasukan untuk mengamankan qilin. Selain itu, hewan ini nantinya akan dibawa dalam pemilihan kepemimpinan dunia sihir.\r Para anggota dari kelompok Dumbledore terdiri dari saudara Scamander, Theseus, penyihir Amerika yakni Lally, Yusuf Kama, seorang muggle yaitu Jacob Kowalski dan Tina.\r Dumbledore mempersiapkan beberapa koper untuk anggota tersebut, di mana salah satunya berisi qilin. Kali ini, anda bisa menebak siapa diantara mereka yang membawa hewan ajaib tersebut.', '2022-04-06', 1708, 7),
(122, 'Morbius', '7', 'https://image.tmdb.org/t/p/w200/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg', 'Sinopsis film Morbius mengisahkan sosok Michael Morbius (Jared Let), seorang dokter yang mencari cara untuk bisa menyembuhkan penyakit darah langka miliknya. Lewat sebuah eksperimen, penyakit darah langka itu akhirnya bisa sembuh', '2022-03-30', 12345678, 10),
(123, 'Sonic the Hedgehog 2', '4', 'https://image.tmdb.org/t/p/w200/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', 'Alur cerita film Sonic the Hedgehog 2 bermula ketika Sonic menetap di Green Hills. Ia memutuskan menetap di sana agar bisa merasakan lebih banyak kebebasan. Ditambah lagi, Tom dan Maddie setuju untuk meninggalakannya di rumah ketika mereka pergi untuk berlibur. Namun sayangnya, tidak lama setelah mereka pergi Dr. Robotnik sang musuh bubuyutan si landak biru itu kembali ke bumi. Kali ini Dr. Robotnik datang dengan pasukan baru, Knuckles. Tujuan mereka datang kembali adalah untuk mencari Master Emerald yang memiliki kekuatan super. Kekuatan super itu bisa membangun dan menghancurkan peradaban di bumi. Atas hal ini, Sonic pun mencari strategi agar bisa menggagalkan rencara Dr. Robotnik. Strategi yang dilakukan oleh Sonic ialah bekerjasama dengan sahabatnya, Tails. Kemudian bersama dengan Tails, Sonic memulai perjalanan untuk menemukan Master Emerald. Semua itu dilakukan dengan cepat, sebelum Master Emerald jatuh ke tangan yang salah.', '2022-03-30', 13765, 7.2),
(124, 'The Lost City', '3', 'https://image.tmdb.org/t/p/w200/neMZH82Stu91d3iqvLdNQfqPPyl.jpg', 'The Lost City mengisahkan tentang seorang penulis novel yang hobi menyendiri bernama Loretta Sage. Ia baru saja menyelesaikan novel romantis terbarunya yang bercerita tentang kota yang hilang. Saat tengah melakukan promosi untuk novel terbarunya, Loretta Sage diculik oleh lelaki bernama Abigail Fairfax.', '2022-03-24', 2345, 6.8),
(125, 'Jurassic World Dominion', '3', 'https://image.tmdb.org/t/p/w200/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg', 'Empat tahun setelah Isla Nublar dihancurkan, dinosaurus sekarang hidup—dan berburu—bersama manusia di seluruh dunia. Keseimbangan yang rapuh ini akan membentuk kembali masa depan dan menentukan, sekali dan untuk semua, apakah manusia akan tetap menjadi predator puncak di planet yang sekarang mereka tempati bersama makhluk paling menakutkan dalam sejarah.', '2022-06-01', 25296, 6.9),
(126, 'Memory', '7', 'https://image.tmdb.org/t/p/w200/QaNLpq3Wuu2yp5ESsXYcQCOpUk.jpg', 'Sinopsis film alam Memory berfokus pada Alex Lewis (Liam Neeso), pembunuh bayaran profesional yang ternyata mengidap alzheimer, penyakit pada otak yang menyebabkan menurunnya daya ingat. Tugas Alex makin rumit ketika ia menyadari bahwa kontrak yang telah dia sepakati mengharuskannya membunuh anak di bawah umur. Dia pun bertekad membatalkan kontrak tersebut dan berbalik memburu orang-orang dalam sindikat kejahatan yang mempekerjakannya. Upaya balas dendam Alex turut diwarnai aksi pengejaran oleh agen FBI Vincent Serra (Guy Pearc), dan intel dari Meksiko. Pada saat yang sama, Alex harus berjuang mempertahankan daya ingatnya yang makin menurun.', '2022-04-28', 271, 7),
(127, 'The Northman', '7', 'https://image.tmdb.org/t/p/w200/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg', 'Pangeran Amleth berada di ambang menjadi seorang pria ketika ayahnya dibunuh secara brutal oleh pamannya, yang menculik ibu anak laki-laki itu. Dua dekade kemudian, Amleth sekarang menjadi Viking yang menjalankan misi untuk menyelamatkan ibunya, membunuh pamannya dan membalaskan dendam ayahnya.', '2022-04-07', 1474, 7),
(128, 'Doctor Strange in the Multiverse of Madness', '6', 'https://image.tmdb.org/t/p/w200/hq2igFqb31fDqGotz8ZuUfwKgn8.jpg', 'Doctor Strange, dengan bantuan sekutu mistis baik lama maupun baru, melintasi realitas alternatif Multiverse yang membingungkan dan berbahaya untuk menghadapi musuh baru yang misterius.', '2022-06-05', 53728, 7.4),
(129, 'Spider-Man: No Way Home', '6', 'https://image.tmdb.org/t/p/w200/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'Peter Parker menghadapi masalah besar. Hal ini terjadi setelah identitasnya sebagai Spiderman terungkap. Dengan kepergian Tony Stark, Peter Parker pun harus meminta bantuan Doctor Strange agar semua orang bisa melupakan identitasnya sebagai manusia laba-laba.', '2021-12-15', 13459, 8),
(130, 'Moon Knight', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/vKDUmKO6F9bSKKyHhg7YGbgcEeF.jpg', 'Steven Grant menemukan bahwa dia telah diberikan kekuatan dewa bulan Mesir. Tapi dia segera menemukan bahwa kekuatan baru ini dapat menjadi berkat dan kutukan untuk hidupnya yang bermasalah.', '2022-03-30', 28734, 8.2),
(131, 'Uncharted', '6', 'https://image.tmdb.org/t/p/w200/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg', 'menceritakan tentang aksi perburuan harta karun terbesar yang tidak pernah ditemukan. Nathan Drake merupakan seorang bartender yang pintar. Nathan mengaku bahwa dirinya adalah keturunan dari penjelajah kenamaan asal Inggris bernama Sir Francis Drake.', '2022-02-10', 2387, 7),
(132, 'The Batman', '7', 'https://image.tmdb.org/t/p/w200/3VFI3zbuNhXzx7dIbYdmvBLekyB.jpg', 'Ketika seorang pembunuh berantai sadis mulai membunuh tokoh-tokoh politik penting di Gotham, Batman terpaksa menyelidiki korupsi tersembunyi di kota itu dan mempertanyakan keterlibatan keluarganya.', '2022-03-01', 32145, 7.8),
(133, 'Turning Red', '4', 'https://image.tmdb.org/t/p/w200/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg', 'Mei yang berusia tiga belas tahun mengalami kecanggungan menjadi seorang remaja dengan twist – ketika dia terlalu bersemangat, dia berubah menjadi panda merah raksasa.', '2022-03-10', 6192, 7.5),
(134, 'Dilan 1990', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/9jvJd0zbN166hA3caTiTTQ61h6G.jpg', 'Milea (Vanesha Prescilla) bertemu dengan Dilan (Iqbaal Ramadhan) di sebuah SMA di Bandung tahun 1990, saat Milea pindah dari Jakarta ke Bandung. Perkenalan yang tidak biasa membawa Milea mengenal keunikan Dilan, pintar, baik hati, romantis. Cara Dilan mendekati Milea tidak sama dengan teman-teman lelaki lain, bahkan Beni (Brandon Salim), pacar Milea di Jakarta. Perjalanan hubungan mereka tak selalu mulus. Beni, Anhar (Giulio Perangkan), Kang Adi (Refal Hadi) mewarnai perjalanan itu. Dilan membuat Milea percaya ia bisa tiba di tujuan dengan selamat.', '2018-01-25', 20873, 7.5),
(135, 'Dilan 1991', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/cWYFRd4XxB2ZNxIZ9HWMsf3eZjE.jpg', '22 Desember 1990, Dilan (Iqbaal Ramadhan) dan Milea (Vanesha Prescilla) resmi berpacaran. Ditengah kebahagiaan mereka Dilan terancam dipecat dari sekolah akibat perkelahian dengan Anhar (Giulio Parengkuan). Dilan juga semakin sering berkelahi dan mendapatkan musuh.Milea khawatir dengan masa depan Dilan. Milea merasa berhak melarang Dilan terlibat dalam geng motor. Suatu ketika, Dilan dikeroyok oleh orang tak dikenal. Saat mengetahui siapa yang berbuat, Dilan merencanakan balas dendam. Milea akhirnya meminta Dilan berhenti dari geng motor atau hubungan mereka berakhir. Dilan, seorang panglima tempur dan ketua geng motor, akan selalu terlibat masalah. Di tengah semua masalah itu, hadir Yugo (Jerome Kurnia), anak dari sepupu jauh ayah Milea yang baru pulang dari Belgia. Mereka sering menghabiskan waktu bersama. Yugo menyukai Milea. Dan Milea...hanya mencintai Dilan.', '2019-02-28', 13245, 6.7),
(136, 'The Bad Guys', '4', 'https://image.tmdb.org/t/p/w200/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg', 'Ketika Orang-Orang Jahat yang terkenal akhirnya tertangkap setelah bertahun-tahun melakukan pencurian yang tak terhitung jumlahnya dan menjadi penjahat paling dicari di dunia, Tuan Wolf membuat kesepakatan untuk menyelamatkan mereka semua dari penjara.', '2022-03-17', 1279, 7.8),
(137, 'Stranger Things', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uKYUR8GPkKRCksczYDJb3pwZauo.jpg', 'Ketika seorang bocah lelaki menghilang, sebuah kota kecil mengungkap misteri yang melibatkan eksperimen rahasia, kekuatan gaib yang menakutkan, dan seorang gadis kecil yang aneh.', '2016-07-15', 126398, 8.6),
(138, 'The Shawshank Redemption', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'Dibingkai pada tahun 1940-an untuk pembunuhan ganda istri dan kekasihnya, bankir terhormat Andy Dufresne memulai kehidupan baru di penjara Shawshank, di mana ia menempatkan keterampilan akuntansinya untuk bekerja sebagai sipir amoral. Selama masa tahanannya yang panjang di penjara, Dufresne dikagumi oleh narapidana lain -- termasuk seorang narapidana yang lebih tua bernama Red -- karena integritas dan harapannya yang tak terpadamkan.', '1994-10-14', 108294, 8.7),
(139, 'Hustle', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/fVf4YHHkRfo1uuljpWBViEGmaUQ.jpg', 'Setelah menemukan pemain sekali seumur hidup dengan masa lalu yang sulit di luar negeri, pencari bakat bola basket yang beruntung membawanya pada dirinya sendiri untuk membawa fenomena itu ke Amerika Serikat tanpa persetujuan timnya. Melawan peluang, mereka memiliki satu kesempatan terakhir untuk membuktikan bahwa mereka memiliki apa yang diperlukan untuk berhasil di NBA.', '2022-06-03', 12582, 7.9),
(140, 'Chip \'n Dale: Rescue Rangers', '4', 'https://image.tmdb.org/t/p/w200/7UGmn8TyWPPzkjhLUW58cOUHjPS.jpg', 'Chip \'n Dale: Rescue Rangers adalah film komedi aksi-petualangan live-action/animasi Amerika tahun 2022 berdasarkan karakter Chip dan Dale dan kelanjutan dari serial TV animasi dengan nama yang sama.', '2022-05-18', 4269, 7.9),
(141, 'Coach Carter', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/y3HOTTyM5nLsdUzXFtFCohG28qj.jpg', 'Berdasarkan kisah nyata, di mana kepala pelatih bola basket Richmond High School Ken Carter menjadi berita utama pada tahun 1999 karena mencadangkan timnya yang tak terkalahkan karena hasil akademis yang buruk.', '2005-01-14', 24087, 7.5),
(145, 'Top Gun: Maverick', '3', 'https://image.tmdb.org/t/p/w200/wxP2Mzv9CdjOK6t4dNnFGqIQl0V.jpg', 'Setelah lebih dari tiga puluh tahun mengabdi sebagai salah satu penerbang top Angkatan Laut, dan menghindari kenaikan pangkat yang akan menjatuhkannya, Pete \"Maverick\" Mitchell mendapati dirinya melatih satu detasemen lulusan TOP GUN untuk misi khusus yang tidak ada kehidupan. pilot pernah melihat.', '2022-05-07', 16839, 8.3),
(146, 'Doctor Strange', '6', 'https://image.tmdb.org/t/p/w200/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg', 'Hidup Stephen Vincent Strange (Benedict Cumberbatc), seorang doktor bedah yang pintar namun sombong, mendadak berubah drastis. Sebuah kecelakaan mobil membuat kemampuan tangannya menjadi sangat terbatas. Bertekad untuk menyembuhkan kondisinya, ia pun berpetualang mencari obat untuk memulihkan tangannya.  Perjalanan tersebut mempertemukan sang doktor bedah dengan penyihir bernama The Ancient One (Tilda Swinto), yang kemudian mengangkat Strange menjadi murid, dengan tujuan menjadikan ia sebagai pelindung alam manusia. Kali ini Strange harus mengesampingkan egonya, dan menggunakan segala kemampuannya untuk menjadi perantara antara dimensi manusia dan dimensi lain.', '2016-10-25', 34123, 7),
(147, 'Encanto', '4', 'https://image.tmdb.org/t/p/w200/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg', 'kisah keluarga luar biasa, Madrigals, yang hidup tersembunyi di pegunungan Kolombia, di rumah ajaib, di kota yang semarak, di tempat yang menakjubkan dan mempesona yang disebut Encanto. Keajaiban Encanto telah memberkati setiap anak dalam keluarga dengan hadiah unik dari kekuatan super hingga kekuatan untuk menyembuhkan—setiap anak kecuali satu, Mirabel. Tetapi ketika dia menemukan bahwa sihir yang mengelilingi Encanto dalam bahaya, Mirabel memutuskan bahwa dia, satu-satunya Madrigal biasa, mungkin hanya harapan terakhir keluarganya yang luar biasa.', '2021-11-24', 6672, 8),
(148, 'A Silent Voice', '5', 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg', 'Sebagai seorang pemuda liar, siswa sekolah dasar Shouya Ishida berusaha untuk mengalahkan kebosanan dengan cara yang paling kejam. Ketika Shouko Nishimiya yang tuli pindah ke kelasnya, Shouya dan seluruh kelasnya tanpa berpikir menggertaknya untuk bersenang-senang. Namun, ketika ibunya memberi tahu sekolah, dia dipilih dan disalahkan atas semua yang dilakukan padanya. Dengan Shouko pindah dari sekolah, Shouya ditinggalkan oleh belas kasihan teman-teman sekelasnya. Dia tanpa perasaan dikucilkan di seluruh sekolah dasar dan menengah, sementara para guru menutup mata.\r\n\r\nSekarang di tahun ketiga sekolah menengahnya, Shouya masih diganggu oleh kesalahannya sebagai anak muda. Dengan tulus menyesali tindakan masa lalunya, dia memulai perjalanan penebusan: untuk bertemu Shouko sekali lagi dan menebus kesalahan.', '2016-09-07', 13789, 8.95),
(149, 'Your Name.', '5', 'https://cdn.myanimelist.net/images/anime/3/87049.jpg', 'Mitsuha Miyamizu, seorang gadis sekolah menengah, mendambakan untuk menjalani kehidupan seorang anak laki-laki di kota Tokyo yang ramai—sebuah mimpi yang sangat kontras dengan kehidupannya saat ini di pedesaan. Sementara itu di kota, Taki Tachibana menjalani kehidupan yang sibuk sebagai siswa sekolah menengah sambil menyulap pekerjaan paruh waktu dan harapan untuk masa depan dalam arsitektur.\r\n\r\nSuatu hari, Mitsuha terbangun di sebuah ruangan yang bukan miliknya dan tiba-tiba mendapati dirinya menjalani kehidupan impian di Tokyo—tetapi di dalam tubuh Taki! Di tempat lain, Taki mendapati dirinya menjalani kehidupan Mitsuha di pedesaan yang sederhana. Dalam mengejar jawaban atas fenomena aneh ini, mereka mulai mencari satu sama lain.', '2016-08-26', 12873, 8.87),
(150, 'Spy x Family', '5', 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg', 'Ceritanya mengikuti mata-mata yang harus \"membangun keluarga\" untuk menjalankan misi, tidak menyadari bahwa gadis yang dia adopsi sebagai anak perempuan dan wanita yang dia setujui untuk menikah palsu dengannya masing-masing adalah pembaca pikiran dan pembunuh.', '2022-04-09', 31342, 9.02),
(151, 'Demon Slayer - Kimetsu no Yaiba - The Movie: Mugen Train', '5', 'https://image.tmdb.org/t/p/w200/m9cn5mhW519QKr1YGpGxNWi98VJ.jpg', 'Tanjirou Kamado dan teman-temannya Pembasmi Iblis menemani Hashira Api Kyoujirou Rengoku, untuk menyelidiki kasus misterius yang terjadi di dalam kereta. Tak banyak yang mereka ketahui tentang keberadaan Enmu, salah satu dari Dua Belas Kizuki yang juga berada di dalam kereta dan telah menyiapkan perangkap untuk mereka.', '2020-10-16', 2464, 8),
(152, 'Jujutsu Kaisen', '5', 'https://cdn.myanimelist.net/images/anime/1046/107701.jpg', 'Seorang anak laki-laki menelan jimat terkutuk jari setan dan menjadi terkutuk sendiri. Dia memasuki sekolah dukun untuk dapat menemukan bagian tubuh iblis lainnya dan dengan demikian mengusir dirinya sendiri.', '2022-10-03', 28980, 8.6),
(153, 'Money Heist', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/sbdIs3PVa2tRMIR0Y2LsTMpWIse.jpg', '8 pencuri melakukan penyanderaan dan mengunci diri mereka di Badan Percetakan Uang Spanyol sementara otak utama kejahatan mengakali polisi agar mewujudkan rencananya.', '2017-05-02', 78269, 8.3),
(154, 'Fullmetal Alchemist: Brotherhood', '5', 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg', 'Setelah eksperimen alkimia yang mengerikan gagal di rumah tangga Elric, saudara laki-laki Edward dan Alphonse ditinggalkan dalam kenyataan baru yang membawa bencana. Mengabaikan prinsip alkimia yang melarang transmutasi manusia, anak-anak lelaki itu berusaha menghidupkan kembali ibu mereka yang baru saja meninggal. Sebaliknya, mereka menderita kerugian pribadi yang brutal: tubuh Alphonse hancur sementara Edward kehilangan satu kaki dan kemudian mengorbankan lengan untuk menjaga jiwa Alphonse di alam fisik dengan mengikatnya ke baju zirah raksasa.  Saudara-saudara diselamatkan oleh tetangga mereka Pinako Rockbell dan cucunya Winry. Dikenal sebagai ahli teknik bio-mekanik, Winry menciptakan kaki palsu untuk Edward dengan memanfaatkan \"automail\", logam tangguh dan serbaguna yang digunakan dalam robot dan baju perang. Setelah bertahun-tahun pelatihan, Elric bersaudara memulai pencarian untuk memulihkan tubuh mereka dengan menemukan Batu Bertuah — permata kuat yang memungkinkan seorang alkemis menentang hukum tradisional Pertukaran Setara.  Saat Edward menjadi seorang alkemis terkenal dan mendapat julukan \"Fullmetal,\" perjalanan anak laki-laki itu melibatkan mereka dalam konspirasi yang berkembang yang mengancam nasib dunia.', '2009-04-05', 18453, 9.14),
(155, 'Steins;Gate', '5', 'https://cdn.myanimelist.net/images/anime/5/73199.jpg', 'Ilmuwan eksentrik Rintarou Okabe memiliki kehausan yang tiada habisnya akan eksplorasi ilmiah. Bersama dengan temannya yang bodoh tapi bermaksud baik Mayuri Shiina dan teman sekamarnya Itaru Hashida, Rintarou mendirikan Laboratorium Gadget Masa Depan dengan harapan dapat menciptakan inovasi teknologi yang membingungkan jiwa manusia. Terlepas dari klaim keagungan, satu-satunya \"gadget\" terkenal yang dibuat oleh ketiganya adalah microwave yang memiliki kekuatan ajaib untuk mengubah pisang menjadi goo hijau.\r\n\r\nNamun, ketika Rintarou memutuskan untuk menghadiri konferensi ahli saraf Kurisu Makise tentang perjalanan waktu, dia mengalami serangkaian peristiwa aneh yang membuatnya percaya bahwa ada lebih banyak hal di gadget \"Mikrowave Telepon\" daripada yang terlihat. Rupanya mampu mengirim pesan teks ke masa lalu menggunakan microwave, Rintarou mencoba lebih jauh dengan \"mesin waktu\", menarik kemarahan dan perhatian dari organisasi misterius SERN.\r\n\r\nKarena penemuan baru, Rintarou dan teman-temannya menemukan diri mereka dalam bahaya yang selalu ada. Saat dia bekerja untuk mengurangi kerusakan yang disebabkan penemuannya pada timeline, dia tidak hanya berjuang untuk menyelamatkan orang yang dicintainya, tetapi juga melawan kewarasannya yang merendahkan.', '2022-04-29', 12935, 9.08),
(156, 'Shikimori\'s Not Just a Cutie', '5', 'https://cdn.myanimelist.net/images/anime/1995/121695.jpg', 'Yuu Izumi menjalani kehidupan sekolah menengah yang penuh dengan kecelakaan demi kecelakaan. Tidak peduli betapa tidak mungkinnya situasinya, peristiwa-peristiwa yang tidak menguntungkan menimpanya di setiap kesempatan. Memiliki nasib buruk seperti itu, Izumi memasuki tahun keduanya dengan satu keinginan dalam pikirannya — untuk menghabiskan lebih banyak waktu dengan pacarnya yang penuh kasih sayang, Micchon Shikimori.  Imut, atletis, dan perhatian, Shikimori sangat populer di sekolah mereka. Tapi sejak mereka mulai berkencan setahun yang lalu, Izumi telah menyaksikan sisi mengejutkan dari pacarnya yang menggemaskan: ketika dibutuhkan, dia menjadi sangat keren! Kemalangannya dengan mudah dihindari ketika dia ada di sana untuk melindunginya dengan ekspresi menakjubkan di wajahnya. Menawan dalam segala hal, dia tidak pernah berhenti membuat jantungnya berdetak kencang. Sayangnya, Izumi pasti akan melihat hari-hari sialnya berakhir berkat Shikimori yang imut namun keren.', '2022-04-09', 6731, 6.88),
(157, 'Hotel Transylvania: Transformania', '4', 'https://image.tmdb.org/t/p/w200/6zt5l4DYV1kLPL5Vqz1kLq3THXD.jpg', 'Ketika penemuan misterius Van Helsing, \"Monsterfication Ray,\" menjadi kacau, Drac dan teman-teman monsternya semuanya berubah menjadi manusia, dan Johnny menjadi monster. Dalam tubuh baru mereka yang tidak serasi, Drac dan Johnny harus bekerja sama dan berlomba melintasi dunia untuk menemukan obat sebelum terlambat, dan sebelum mereka saling membuat gila.', '2022-02-25', 9693, 7.1),
(158, 'The Valet', '3', 'https://image.tmdb.org/t/p/w200/q7FmdJHKMLIC4XgWfcFRIu2iVdL.jpg', 'Bintang film terkenal dunia Olivia menghadapi bencana PR ketika paparazzi mengambil foto dirinya dengan kekasihnya yang sudah menikah, Vincent. Pelayan pekerja keras Antonio secara tidak sengaja muncul di foto yang sama dan diminta untuk berpose sebagai pacar baru Olivia sebagai penutup. Tipuan dengan Olivia ini mendorong Antonio menjadi sorotan dan kekacauan yang tak terduga.', '2022-05-11', 1834, 8),
(159, 'Goal!', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/9YZhJGoIbJtrjDYbENGhR6f6SZE.jpg', 'Seperti jutaan anak di seluruh dunia, Santiago memiliki impian menjadi pesepakbola profesional... Namun, tinggal di bagian Barrios di Los Angeles, dia pikir itu hanya—sebuah mimpi. Sampai suatu hari, kejadian luar biasa membuatnya mencoba untuk klub Liga Utama Newcastle United.', '2005-09-25', 16495, 6.6),
(160, 'The Seven Deadly Sins: Terkutuk oleh Cahaya', '5', 'https://image.tmdb.org/t/p/w200/8AnML0t6LreZyiQ1kVkJVzoGltZ.jpg', 'Meliodas dan kawan-kawannya kembali beraksi ketika era baru yang penuh kedamaian terancam oleh aliansi sihir hebat yang bisa mengakhiri segalanya.', '2021-07-02', 3023, 8),
(161, 'Fireheart', '4', 'https://image.tmdb.org/t/p/w200/hepwOZWJNUmLzB68gKYEdEJAaD3.jpg', 'Film ini mengeksplorasi dunia petugas pemadam kebakaran di New York City tahun 1920-an dan menceritakan kisah seorang gadis berusia 16 tahun yang harus menjadi pahlawan untuk menyelamatkan kotanya.', '2022-01-16', 6213, 7.6),
(162, 'Ada Apa Dengan Cinta? 2', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/nN50NGt2yvIcoklrIzF1UIEF4TH.jpg', 'Cinta dan Rangga, dua orang remaja yang saling mencintai terpisahkan 14 tahun yang lalu. Kini, setelah bertahun-tahun, Rangga dan Cinta mendapatkan kesempatan untuk kembali bertemu. Akankah ini menjadi kesempatan kedua untuk mereka kembali bersama? Apalagi hidup mereka tidak lagi sesederhana dulu.', '2016-04-28', 25132, 5.9),
(163, 'Jurassic World', '3', 'https://image.tmdb.org/t/p/w200/A0LZHXUzo5C60Oahvt7VxvwuzHw.jpg', 'Dua puluh dua tahun setelah peristiwa Jurassic Park, Isla Nublar sekarang memiliki taman hiburan dinosaurus yang berfungsi penuh, Jurassic World, seperti yang awalnya dibayangkan oleh John Hammond.', '2015-06-06', 23612, 6.7),
(164, 'Silverton Siege', '7', 'https://image.tmdb.org/t/p/w200/5HruMN0vvl84AqD7sCDXFNO4RhP.jpg', 'Setelah misi sabotase yang gagal, trio pejuang kemerdekaan anti-apartheid berakhir dalam situasi penyanderaan bank yang tegang. Berdasarkan kisah nyata.', '2022-04-27', 2345, 6.6),
(165, '50 Shades of Grey', '8', 'https://upload.wikimedia.org/wikipedia/en/7/73/Fifty_Shades_of_Grey_poster.jpg', 'Kehidupan mahasiswa sastra Anastasia Steele berubah selamanya ketika dia bertemu miliarder tampan, namun tersiksa, Christian Grey.', '2015-02-13', 78935, 4.1),
(167, 'Venom:Let There be Carnage', '7', 'https://image.tmdb.org/t/p/w200/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg', 'Venom kembali beraksi ketika pembunuh berantai terkenal Cletus Cassidy menjadi pembantaian yang kejam.', '2021-09-30', 13576, 7),
(168, 'Interceptor', '7', 'https://image.tmdb.org/t/p/w200/cpWUtkcgRKeauhTyVMjYHxAutp4.jpg', 'Seorang letnan Angkatan Darat menggunakan pelatihan taktisnya selama bertahun-tahun untuk menyelamatkan umat manusia dari enam belas rudal nuklir yang diluncurkan di AS saat serangan terkoordinasi dengan kekerasan secara bersamaan mengancam stasiun pencegat rudal jarak jauhnya.', '2022-05-26', 3544, 6.8),
(170, 'Peaky Blinders', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/bGZn5RVzMMXju4ev7xbl1aLdXqq.jpg', 'Sebuah epik keluarga gangster berlatar di Birmingham, Inggris pada tahun 1919 dan berpusat pada sebuah geng yang menjahit pisau silet di puncak topi mereka, dan bos mereka yang garang Tommy Shelby, yang bermaksud untuk naik ke dunia.', '2013-09-12', 156348, 8.6),
(171, 'Teen Titans Go! & DC Super Hero Girls: Mayhem in the Multiverse', '4', 'https://image.tmdb.org/t/p/w200/3Hnhf1FqVGnh20hKlHbiRvHhB5b.jpg', 'Dengan bantuan kekuatan Krypton kuno, Lex Luthor menyatukan Penjahat Super dunia untuk menangkap semua Pahlawan Super Bumi, sampai…hanya Gadis Pahlawan Super DC yang tersisa untuk menghentikan Legion of Doom. Pahlawan kita harus melintasi dimensi untuk menyelamatkan sesama Pahlawan Super mereka dari Zona Phantom, tetapi kesalahan yang tidak disengaja membawa mereka ke Menara Titans – di mana mereka menemukan sekutu yang sangat dibutuhkan di Titan Remaja!', '2022-05-23', 5632, 7.2),
(172, 'Top Gun', '3', 'https://image.tmdb.org/t/p/w200/56XAyRDe8UpeAb7QKdqyERpXhTM.jpg', 'Bagi Letnan Pete \'Maverick\' Mitchell dan temannya serta co-pilot Nick \'Goose\' Bradshaw, diterima di sekolah pelatihan elit untuk pilot pesawat tempur adalah mimpi yang menjadi kenyataan. Tapi sebuah tragedi, serta setan pribadi, akan mengancam impian Pete untuk menjadi pilot ace.', '1986-05-16', 120420, 7),
(173, 'Jurassic World: Fallen Kingdom', '3', 'https://image.tmdb.org/t/p/w200/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg', 'Setelah Isla Nublar porak-poranda akibat letusan gunung berapi, spesies dinosaurus yang tersisa dibawa ke perkebunan Lockwood yang besar, di Amerika. Di tempat tersebut, Owen dan Claire menyadari bahwa spesies dinosaurus malah dilelang dan tidak dilestarikan. Seekor dinosaurus hibrida yang sangat berbahaya dan dikenal dengan nama Indoraptor, kabur dan mulai meneror penduduk di sekitar perkebunan.', '2018-06-06', 9922, 7),
(174, 'Sing 2', '4', 'https://image.tmdb.org/t/p/w200/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg', 'Buster dan pemain barunya sekarang memiliki pandangan untuk memulai debut pertunjukan baru di Crystal Tower Theatre di Redshore City yang glamor. Tapi tanpa koneksi, dia dan penyanyinya harus menyelinap ke kantor Crystal Entertainment, yang dijalankan oleh maestro serigala kejam Jimmy Crystal, di mana geng itu melontarkan ide konyol untuk memasukkan legenda rock singa Clay Calloway dalam pertunjukan mereka. Buster harus memulai pencarian untuk menemukan Clay yang sekarang terisolasi dan membujuknya untuk kembali ke panggung.', '2021-12-01', 3412, 8.1),
(175, 'Ada Apa Dengan Cinta?', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/v7HMMGgWqxeIObCMouvU8mWPWCv.jpg', 'Bertemakan cinta di masa-masa SMA, Ada Apa dengan Cinta menampilkan Cinta (Dian Sastrowardoyo) sebagai seorang pelajar SMA. Ia langganan juara lomba puisi di sekolahnya yang rutin diadakan tiap tahun. Cerita berawal dari Alya (Ladya Cherill) yang tubuhnya memar karena kerap dipukuli sang ayah yang kerap cek-cok dengan ibunya. Alya adalah sahabat karib Cinta dengan teman-temannya yang lain seperti Carmen (Adinia Wirasti), Maura (Titi Kamal), dan Milly (Sissy Priscillia)', '2002-02-08', 59312, 7.6);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `film`
--
ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=181;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;



